package com.iqbase.iqbase.view;

import com.iqbase.iqbase.Produto;
import javax.swing.JOptionPane;

public class TelaNovoProduto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaNovoProduto.class.getName());

    private Produto novoProduto = null;

    public TelaNovoProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCampos = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        lblEstoque = new javax.swing.JLabel();
        campoEstoque = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Novo Produto");
        setPreferredSize(new java.awt.Dimension(400, 250));

        painelCampos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        painelCampos.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        lblNome.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        lblNome.setText("Nome:");
        painelCampos.add(lblNome);
        painelCampos.add(campoNome);

        lblDescricao.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        lblDescricao.setText("Descrição:");
        painelCampos.add(lblDescricao);
        painelCampos.add(campoDescricao);

        lblPreco.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        lblPreco.setText("Preço (ex: 9.99):");
        painelCampos.add(lblPreco);
        painelCampos.add(campoPreco);

        lblEstoque.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        lblEstoque.setText("Estoque Inicial:");
        painelCampos.add(lblEstoque);
        painelCampos.add(campoEstoque);

        painelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(this::botaoSalvarActionPerformed);
        painelBotoes.add(botaoSalvar);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(this::botaoCancelarActionPerformed);
        painelBotoes.add(botaoCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        salvarProduto();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void salvarProduto() {
        // Validação simples
        if (campoNome.getText().trim().isEmpty() || campoPreco.getText().trim().isEmpty() || 
            campoEstoque.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome, Preço e Estoque são obrigatórios.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String nome = campoNome.getText().trim();
            String desc = campoDescricao.getText().trim();
            double preco = Double.parseDouble(campoPreco.getText().trim().replace(",", "."));
            int estoque = Integer.parseInt(campoEstoque.getText().trim());
            
            // O código será gerado pelo DAO, então passamos uma string vazia ou null
            this.novoProduto = new Produto("", nome, desc, preco, estoque);
            dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Preço e Estoque devem ser números válidos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Produto getProduto() {
        return this.novoProduto;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaNovoProduto dialog = new TelaNovoProduto(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoEstoque;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCampos;
    // End of variables declaration//GEN-END:variables
}
