package com.iqbase.iqbase.view;

import com.iqbase.iqbase.Funcionario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

public class TelaNovoFuncionario extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaNovoFuncionario.class.getName());

    private Funcionario novoFuncionario;
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public TelaNovoFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        radioMasculino.setSelected(true); // Seleção padrão
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        painelCampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        lblDataNasc = new javax.swing.JLabel();
        campoDataNascimento = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        painelSexo = new javax.swing.JPanel();
        radioMasculino = new javax.swing.JRadioButton();
        radioFeminino = new javax.swing.JRadioButton();
        lblCargo = new javax.swing.JLabel();
        campoCargo = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        botaoProximo = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados do Novo Funcionário");

        painelCampos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        painelCampos.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel1.setText("Nome:");
        painelCampos.add(jLabel1);
        painelCampos.add(campoNome);

        lblDataNasc.setText("Data Nascimento (dd/MM/yyyy):");
        painelCampos.add(lblDataNasc);
        painelCampos.add(campoDataNascimento);

        lblSexo.setText("Sexo:");
        painelCampos.add(lblSexo);

        painelSexo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        grupoSexo.add(radioMasculino);
        radioMasculino.setText("Masculino");
        painelSexo.add(radioMasculino);

        grupoSexo.add(radioFeminino);
        radioFeminino.setText("Feminino");
        painelSexo.add(radioFeminino);

        painelCampos.add(painelSexo);

        lblCargo.setText("Cargo");
        painelCampos.add(lblCargo);
        painelCampos.add(campoCargo);

        painelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botaoProximo.setText("Próximo");
        botaoProximo.addActionListener(this::botaoProximoActionPerformed);
        painelBotoes.add(botaoProximo);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(this::botaoCancelarActionPerformed);
        painelBotoes.add(botaoCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed
        salvarDadosIniciais();
    }//GEN-LAST:event_botaoProximoActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        novoFuncionario = null; // Garante que nenhum funcionário seja retornado se cancelar
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed
    
    private void salvarDadosIniciais() {
        try {
            String nome = campoNome.getText();
            if (nome.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O nome não pode estar vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            LocalDate dataNascimento = LocalDate.parse(campoDataNascimento.getText(), DATE_FORMATTER);
            
            String sexo;
            if (radioMasculino.isSelected()) {
                sexo = "Masculino";
            } else if (radioFeminino.isSelected()) {
                sexo = "Feminino";
            } else {
                JOptionPane.showMessageDialog(this, "Selecione o sexo do funcionário.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String cargo = campoCargo.getText();

            // Cria o funcionário com credenciais nulas por enquanto
            novoFuncionario = new Funcionario(0, nome, dataNascimento, sexo, cargo, null, null);
            
            dispose(); // Fecha esta janela para abrir a próxima

        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use dd/MM/yyyy.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Funcionario getFuncionario() {
        return novoFuncionario;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaNovoFuncionario dialog = new TelaNovoFuncionario(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JTextField campoCargo;
    private javax.swing.JTextField campoDataNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelSexo;
    private javax.swing.JRadioButton radioFeminino;
    private javax.swing.JRadioButton radioMasculino;
    // End of variables declaration//GEN-END:variables
}
