
package com.iqbase.iqbase.view;

import javax.swing.JOptionPane;

public class TelaMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenu.class.getName());

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza a janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        botaoNovaVenda = new javax.swing.JButton();
        botaoVerEstoque = new javax.swing.JButton();
        botaoGerenciarFuncionarios = new javax.swing.JButton();
        botaoSobreSistema = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal - IQBase");

        painel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 20, 50));
        painel.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        botaoNovaVenda.setText("Nova Venda");
        botaoNovaVenda.addActionListener(this::botaoNovaVendaActionPerformed);
        painel.add(botaoNovaVenda);

        botaoVerEstoque.setText("Ver Estoque");
        botaoVerEstoque.addActionListener(this::botaoVerEstoqueActionPerformed);
        painel.add(botaoVerEstoque);

        botaoGerenciarFuncionarios.setText("Gerenciar Funcionários");
        botaoGerenciarFuncionarios.addActionListener(this::botaoGerenciarFuncionariosActionPerformed);
        painel.add(botaoGerenciarFuncionarios);

        botaoSobreSistema.setText("Sobre o Sistema");
        botaoSobreSistema.addActionListener(this::botaoSobreSistemaActionPerformed);
        painel.add(botaoSobreSistema);

        botaoSair.setText("Sair");
        botaoSair.addActionListener(this::botaoSairActionPerformed);
        painel.add(botaoSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovaVendaActionPerformed
        new TelaVenda(this, true).setVisible(true);
    }//GEN-LAST:event_botaoNovaVendaActionPerformed

    private void botaoVerEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerEstoqueActionPerformed
        new TelaEstoque(this, true).setVisible(true);
    }//GEN-LAST:event_botaoVerEstoqueActionPerformed

    private void botaoGerenciarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerenciarFuncionariosActionPerformed
        new TelaGerenciarFuncionarios(this, true).setVisible(true);
    }//GEN-LAST:event_botaoGerenciarFuncionariosActionPerformed

    private void botaoSobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreSistemaActionPerformed
        new TelaSobre(this, true).setVisible(true);
    }//GEN-LAST:event_botaoSobreSistemaActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja sair do sistema?", 
            "Confirmar Saída", 
            JOptionPane.YES_NO_OPTION
        );
            
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerenciarFuncionarios;
    private javax.swing.JButton botaoNovaVenda;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSobreSistema;
    private javax.swing.JButton botaoVerEstoque;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
