
package com.iqbase.iqbase.view;

import com.iqbase.iqbase.Produto;
import com.iqbase.iqbase.ProdutoDAO;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class TelaPesquisaProduto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPesquisaProduto.class.getName());

    private DefaultListModel<Produto> modeloLista;
    private Produto produtoSelecionado;

    /**
     * @deprecated Use o construtor que recebe o DAO e o termo de busca
     */
    @Deprecated
    public TelaPesquisaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public TelaPesquisaProduto(java.awt.Dialog parent, boolean modal, ProdutoDAO produtoDAO, String termoBusca) {
        super(parent, modal);
        initComponents();
        
        this.modeloLista = new DefaultListModel<>();
        this.listaResultados.setModel(modeloLista);
        this.listaResultados.setCellRenderer(new ProdutoListCellRenderer());
        
        realizarBusca(produtoDAO, termoBusca);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        listaResultados = new javax.swing.JList<Produto>();
        painelBotoes = new javax.swing.JPanel();
        botaoAdicionar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultados da Pesquisa:");
        setSize(new java.awt.Dimension(500, 400));

        listaResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados:"));
        listaResultados.setToolTipText("");
        scrollPane.setViewportView(listaResultados);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        painelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botaoAdicionar.setText("Adicionar à Venda");
        botaoAdicionar.addActionListener(this::botaoAdicionarActionPerformed);
        painelBotoes.add(botaoAdicionar);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(this::botaoCancelarActionPerformed);
        painelBotoes.add(botaoCancelar);

        getContentPane().add(painelBotoes, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        produtoSelecionado = listaResultados.getSelectedValue();
        if (produtoSelecionado != null) {
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto da lista.", "Nenhum Produto Selecionado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        produtoSelecionado = null;
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void realizarBusca(ProdutoDAO produtoDAO, String termoBusca) {
        List<Produto> resultados = produtoDAO.buscarPorNome(termoBusca);
        // Se a busca por nome não retornar nada, tenta buscar por código
        if (resultados.isEmpty()) {
            Produto p = produtoDAO.buscarPorCodigo(termoBusca);
            if (p != null) {
                resultados.add(p);
            }
        }

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum produto encontrado para '" + termoBusca + "'.", "Busca Sem Resultados", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            for (Produto p : resultados) {
                modeloLista.addElement(p);
            }
        }
    }
    
    public Produto getProdutoSelecionado() {
        return produtoSelecionado;
    }

    // Custom Cell Renderer para mostrar o nome e o preço do produto na lista
    private static class ProdutoListCellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof Produto) {
                Produto produto = (Produto) value;
                setText(String.format("%s (Cód: %s) - R$ %.2f", produto.getNome(), produto.getCodigo(), produto.getPrecoUnitario()));
            }
            return this;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaPesquisaProduto dialog = new TelaPesquisaProduto(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JList<Produto> listaResultados;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
