
package com.iqbase.iqbase.view;

import com.iqbase.iqbase.ItemVenda;
import com.iqbase.iqbase.Produto;
import com.iqbase.iqbase.ProdutoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaVenda extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVenda.class.getName());

    private DefaultTableModel modeloTabela;
    private ProdutoDAO produtoDAO;
    private List<ItemVenda> itensVenda;
    private double totalVenda;

    public TelaVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        produtoDAO = new ProdutoDAO();
        itensVenda = new ArrayList<>();
        totalVenda = 0.0;
        
        // Configura a tabela
        String[] colunas = {"Código", "Nome", "Qtd", "Preço Unit.", "Preço Total"};
        modeloTabela = new DefaultTableModel(colunas, 0);
        tabelaItensVenda.setModel(modeloTabela);
        
        // Adiciona listeners para os campos de texto (ação com Enter)
        ActionListener acaoAdicionar = e -> adicionarProdutoPeloCodigo(campoCodigoProduto.getText());
        campoCodigoProduto.addActionListener(acaoAdicionar);
        
        ActionListener acaoPesquisar = e -> pesquisarProduto();
        campoPesquisaProduto.addActionListener(acaoPesquisar);
        
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        painelPesquisa = new javax.swing.JPanel();
        lblCodigoProduto = new javax.swing.JLabel();
        campoCodigoProduto = new javax.swing.JTextField();
        botaoAdicionarProduto = new javax.swing.JButton();
        painelEntrada = new javax.swing.JPanel();
        lblNomeCodigo = new javax.swing.JLabel();
        campoPesquisaProduto = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        painelCentral = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tabelaItensVenda = new javax.swing.JTable();
        painelOpcoes = new javax.swing.JPanel();
        botaoVerTabelaProdutos = new javax.swing.JButton();
        botaoRemoverItem = new javax.swing.JButton();
        painelInferior = new javax.swing.JPanel();
        labelTotalVenda = new javax.swing.JLabel();
        painelBotoesFinais = new javax.swing.JPanel();
        botaoCancelarVenda = new javax.swing.JButton();
        botaoFinalizarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        painelSuperior.setLayout(new java.awt.BorderLayout(10, 10));

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Produto"));
        painelPesquisa.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblCodigoProduto.setText("Código do Produto:");
        painelPesquisa.add(lblCodigoProduto);

        campoCodigoProduto.setColumns(10);
        campoCodigoProduto.addActionListener(this::campoCodigoProdutoActionPerformed);
        painelPesquisa.add(campoCodigoProduto);

        botaoAdicionarProduto.setText("Adicionar");
        botaoAdicionarProduto.addActionListener(this::botaoAdicionarProdutoActionPerformed);
        painelPesquisa.add(botaoAdicionarProduto);

        painelSuperior.add(painelPesquisa, java.awt.BorderLayout.EAST);

        painelEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Produto"));
        painelEntrada.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblNomeCodigo.setText("Nome ou Código:");
        painelEntrada.add(lblNomeCodigo);

        campoPesquisaProduto.setColumns(10);
        campoPesquisaProduto.addActionListener(this::campoPesquisaProdutoActionPerformed);
        painelEntrada.add(campoPesquisaProduto);

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(this::botaoPesquisarActionPerformed);
        painelEntrada.add(botaoPesquisar);

        painelSuperior.add(painelEntrada, java.awt.BorderLayout.WEST);

        getContentPane().add(painelSuperior, java.awt.BorderLayout.NORTH);

        painelCentral.setLayout(new java.awt.BorderLayout(10, 10));

        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens da Venda"));

        tabelaItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Qtd.", "Preço Unit.", "Preço Total"
            }
        ));
        scrollPane.setViewportView(tabelaItensVenda);

        painelCentral.add(scrollPane, java.awt.BorderLayout.CENTER);

        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));
        painelOpcoes.setLayout(new javax.swing.BoxLayout(painelOpcoes, javax.swing.BoxLayout.Y_AXIS));

        botaoVerTabelaProdutos.setText("Ver Produtos");
        botaoVerTabelaProdutos.addActionListener(this::botaoVerTabelaProdutosActionPerformed);
        painelOpcoes.add(botaoVerTabelaProdutos);

        botaoRemoverItem.setText("Remover Item");
        botaoRemoverItem.addActionListener(this::botaoRemoverItemActionPerformed);
        painelOpcoes.add(botaoRemoverItem);

        painelCentral.add(painelOpcoes, java.awt.BorderLayout.EAST);

        getContentPane().add(painelCentral, java.awt.BorderLayout.CENTER);

        painelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        painelInferior.setLayout(new java.awt.BorderLayout());

        labelTotalVenda.setFont(new java.awt.Font("Adwaita Sans", 1, 20)); // NOI18N
        labelTotalVenda.setText("Total: R$ 0,00");
        painelInferior.add(labelTotalVenda, java.awt.BorderLayout.WEST);

        painelBotoesFinais.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botaoCancelarVenda.setText("Cancelar Venda");
        botaoCancelarVenda.addActionListener(this::botaoCancelarVendaActionPerformed);
        painelBotoesFinais.add(botaoCancelarVenda);

        botaoFinalizarVenda.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        botaoFinalizarVenda.setText("Finalizar Venda");
        botaoFinalizarVenda.addActionListener(this::botaoFinalizarVendaActionPerformed);
        painelBotoesFinais.add(botaoFinalizarVenda);

        painelInferior.add(painelBotoesFinais, java.awt.BorderLayout.EAST);

        getContentPane().add(painelInferior, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVerTabelaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerTabelaProdutosActionPerformed
        verTabelaProdutos();
    }//GEN-LAST:event_botaoVerTabelaProdutosActionPerformed

    private void botaoRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverItemActionPerformed
        removerItemVenda();
    }//GEN-LAST:event_botaoRemoverItemActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        pesquisarProduto();
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarProdutoActionPerformed
        adicionarProdutoPeloCodigo(campoCodigoProduto.getText());
    }//GEN-LAST:event_botaoAdicionarProdutoActionPerformed

    private void botaoFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarVendaActionPerformed
        finalizarVenda();
    }//GEN-LAST:event_botaoFinalizarVendaActionPerformed

    private void botaoCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarVendaActionPerformed
        cancelarVenda();
    }//GEN-LAST:event_botaoCancelarVendaActionPerformed

    private void adicionarProdutoPeloCodigo(String codigo) {
        if (codigo == null || codigo.trim().isEmpty()) { return; }
        Produto produto = produtoDAO.buscarPorCodigo(codigo.trim());
        if (produto == null) {
            JOptionPane.showMessageDialog(this, "Produto com o código '" + codigo + "' não encontrado.", "Produto Inexistente", JOptionPane.WARNING_MESSAGE);
            return;
        }
        adicionarProdutoNaVenda(produto);
        campoCodigoProduto.setText("");
        campoCodigoProduto.requestFocus();
    }
    
    private void adicionarProdutoNaVenda(Produto produto) {
        // Verifica se o produto já está na lista
        for (ItemVenda item : itensVenda) {
            if (item.getProduto().getCodigo().equals(produto.getCodigo())) {
                // Verifica se há estoque para adicionar mais uma unidade
                if (item.getProduto().getQuantidadeEstoque() > item.getQuantidade()) {
                    item.setQuantidade(item.getQuantidade() + 1);
                    atualizarTabelaEtotal();
                } else {
                    JOptionPane.showMessageDialog(this, "Estoque insuficiente para '" + produto.getNome() + "'.", "Estoque Insuficiente", JOptionPane.WARNING_MESSAGE);
                }
                return;
            }
        }

        // Se não está na lista, adiciona um novo item se houver estoque
        if (produto.getQuantidadeEstoque() > 0) {
            itensVenda.add(new ItemVenda(produto, 1));
            atualizarTabelaEtotal();
        } else {
            JOptionPane.showMessageDialog(this, "Produto '" + produto.getNome() + "' sem estoque.", "Estoque Esgotado", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void pesquisarProduto() {
        String termoBusca = campoPesquisaProduto.getText();
        if(termoBusca.trim().isEmpty()) { return; }
        TelaPesquisaProduto telaPesquisa = new TelaPesquisaProduto(this, true, produtoDAO, termoBusca);
        telaPesquisa.setVisible(true);
        Produto produtoSelecionado = telaPesquisa.getProdutoSelecionado();
        if (produtoSelecionado != null) {
            adicionarProdutoNaVenda(produtoSelecionado);
            campoPesquisaProduto.setText("");
            campoCodigoProduto.requestFocus();
        }
    }
    
    private void atualizarTabelaEtotal() {
        modeloTabela.setRowCount(0);
        totalVenda = 0;
        for (ItemVenda item : itensVenda) {
            Produto p = item.getProduto();
            double precoTotalItem = item.getPrecoTotal();
            modeloTabela.addRow(new Object[]{p.getCodigo(), p.getNome(), item.getQuantidade(), String.format("R$ %.2f", p.getPrecoUnitario()), String.format("R$ %.2f", precoTotalItem)});
            totalVenda += precoTotalItem;
        }
        labelTotalVenda.setText(String.format("Total: R$ %.2f", totalVenda));
    }
    
    private void verTabelaProdutos() {
        new TelaTabelaProdutos((java.awt.Frame) getOwner(), true).setVisible(true);
    }
    
    private void removerItemVenda() {
        int linhaSelecionada = tabelaItensVenda.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um item para remover.", "Nenhum Item Selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        itensVenda.remove(linhaSelecionada);
        atualizarTabelaEtotal();
    }
    
    private void finalizarVenda() {
        if (itensVenda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum item na venda para finalizar.", "Venda vazia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(this, String.format("Total da venda: R$ %.2f. Deseja finalizar?", totalVenda), "Confirmar Finalização", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            // Lógica para atualizar o estoque
            for(ItemVenda item : itensVenda) {
                Produto produtoVendido = item.getProduto();
                int quantidadeVendida = item.getQuantidade();
                produtoVendido.setQuantidadeEstoque(produtoVendido.getQuantidadeEstoque() - quantidadeVendida);
            }
            
            // Salva as alterações no arquivo de produtos
            produtoDAO.salvarAlteracoes();
            
            JOptionPane.showMessageDialog(this, "Venda finalizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }
    
    private void cancelarVenda() {
        if (!itensVenda.isEmpty()) {
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar a venda atual? Todos os itens serão removidos.", "Cancelar Venda", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.NO_OPTION) {
                return;
            }
        }
        dispose();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaVenda dialog = new TelaVenda(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarProduto;
    private javax.swing.JButton botaoCancelarVenda;
    private javax.swing.JButton botaoFinalizarVenda;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoRemoverItem;
    private javax.swing.JButton botaoVerTabelaProdutos;
    private javax.swing.JTextField campoCodigoProduto;
    private javax.swing.JTextField campoPesquisaProduto;
    private javax.swing.JLabel labelTotalVenda;
    private javax.swing.JLabel lblCodigoProduto;
    private javax.swing.JLabel lblNomeCodigo;
    private javax.swing.JPanel painelBotoesFinais;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelEntrada;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaItensVenda;
    // End of variables declaration//GEN-END:variables

    private void campoCodigoProdutoActionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void campoPesquisaProdutoActionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
