package com.iqbase.iqbase.view;

import com.iqbase.iqbase.Produto;
import com.iqbase.iqbase.ProdutoDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

public class TelaEstoque extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEstoque.class.getName());

    private DefaultTableModel modeloTabela;
    private ProdutoDAO produtoDAO;
    private boolean dadosAlterados = false;

    public TelaEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        produtoDAO = new ProdutoDAO();

        // Configura a tabela com um modelo customizado
        String[] colunas = {"Código", "Nome", "Descrição", "Preço Unit.", "Estoque"};
        modeloTabela = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; // Apenas a coluna 0 (Código) não é editável
            }
        };
        tabelaEstoque.setModel(modeloTabela);
        
        // Listener para detectar alterações na tabela
        modeloTabela.addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                dadosAlterados = true;
            }
        });

        carregarDadosNaTabela();
        
        // Listener para o fechamento da janela
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                fecharJanela();
            }
        });
        
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        lblProdutos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botaoAdicionar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Estoque");

        scrollPane.setToolTipText("");

        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descrição", "Preço Unit", "Estoque"
            }
        ));
        scrollPane.setViewportView(tabelaEstoque);

        lblProdutos.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        lblProdutos.setText("Produtos em Estoque:");

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        botaoAdicionar.setText("Adicionar Novo Produto");
        botaoAdicionar.addActionListener(this::botaoAdicionarActionPerformed);
        jPanel1.add(botaoAdicionar);

        botaoExcluir.setText("Excluir Selecionado");
        botaoExcluir.addActionListener(this::botaoExcluirActionPerformed);
        jPanel1.add(botaoExcluir);

        botaoSalvar.setText("Salvar Alterações");
        botaoSalvar.addActionListener(this::botaoSalvarActionPerformed);
        jPanel1.add(botaoSalvar);

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(this::botaoFecharActionPerformed);
        jPanel1.add(botaoFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProdutos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        adicionarProduto();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        excluirProduto();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        salvarAlteracoes();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        fecharJanela();
    }//GEN-LAST:event_botaoFecharActionPerformed
    
    private void carregarDadosNaTabela() {
        modeloTabela.setRowCount(0); 
        List<Produto> produtos = produtoDAO.getTodosOsProdutos();
        for (Produto p : produtos) {
            modeloTabela.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getDescricao(),
                String.format("%.2f", p.getPrecoUnitario()),
                p.getQuantidadeEstoque()
            });
        }
        dadosAlterados = false;
    }
    
    private void adicionarProduto() {
        TelaNovoProduto telaNovo = new TelaNovoProduto((java.awt.Frame) getOwner(), true);
        telaNovo.setVisible(true);
        
        Produto novoProduto = telaNovo.getProduto();
        if (novoProduto != null) {
            produtoDAO.adicionarProduto(novoProduto);
            carregarDadosNaTabela(); // Recarrega a tabela para mostrar o novo código
            dadosAlterados = true;
        }
    }
    
    private void excluirProduto() {
        int linhaSelecionada = tabelaEstoque.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para excluir.", "Nenhum Produto Selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o produto selecionado?\nIsso reordenará os códigos dos produtos seguintes.", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            produtoDAO.removerProduto(linhaSelecionada);
            carregarDadosNaTabela(); // Recarrega a tabela para mostrar os códigos reordenados
            dadosAlterados = true;
        }
    }
    
    private void salvarAlteracoes() {
        if (tabelaEstoque.isEditing()) {
            tabelaEstoque.getCellEditor().stopCellEditing();
        }

        for (int i = 0; i < modeloTabela.getRowCount(); i++) {
            Produto p = produtoDAO.getProduto(i);
            if(p != null) {
                // O código não é atualizado a partir da tabela
                p.setNome((String) modeloTabela.getValueAt(i, 1));
                p.setDescricao((String) modeloTabela.getValueAt(i, 2));
                try {
                    p.setPrecoUnitario(Double.parseDouble(modeloTabela.getValueAt(i, 3).toString().replace(",", ".")));
                    p.setQuantidadeEstoque(Integer.parseInt(modeloTabela.getValueAt(i, 4).toString()));
                } catch(NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Erro de formato na linha " + (i+1) + ".\nPreço e Estoque devem ser números.", "Erro de Dados", JOptionPane.ERROR_MESSAGE);
                    return; // Interrompe o salvamento
                }
            }
        }
        
        produtoDAO.salvarAlteracoes();
        dadosAlterados = false;
        JOptionPane.showMessageDialog(this, "Alterações salvas com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void fecharJanela() {
        if (dadosAlterados) {
            int resposta = JOptionPane.showConfirmDialog(this, "Você possui alterações não salvas. Deseja salvar antes de sair?", "Alterações Pendentes", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION) {
                salvarAlteracoes();
                dispose();
            } else if (resposta == JOptionPane.NO_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaEstoque dialog = new TelaEstoque(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaEstoque;
    // End of variables declaration//GEN-END:variables
}