package com.iqbase.iqbase.view;

import com.iqbase.iqbase.Funcionario;
import com.iqbase.iqbase.FuncionarioDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;


public class TelaGerenciarFuncionarios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaGerenciarFuncionarios.class.getName());

    private DefaultTableModel modeloTabela;
    private FuncionarioDAO funcionarioDAO;
    private boolean dadosAlterados = false;
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form TelaGerenciarFuncionarios
     */
    public TelaGerenciarFuncionarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        funcionarioDAO = new FuncionarioDAO();

        String[] colunas = {"Código", "Nome", "Data Nascimento", "Sexo", "Cargo", "Usuário", "Senha"};
        modeloTabela = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; // Apenas a coluna 0 (Código) não é editável
            }
        };
        tabelaFuncionarios.setModel(modeloTabela);
        
        modeloTabela.addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                dadosAlterados = true;
            }
        });

        carregarDadosNaTabela();
        
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                fecharJanela();
            }
        });
        
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        lblFuncionariosCadastrados = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botaoAdicionarNovoFuncionario = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Funcionários");

        scrollPane.setToolTipText("");

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data Nascimento", "Sexo", "Cargo", "Usuário", "Senha"
            }
        ));
        scrollPane.setViewportView(tabelaFuncionarios);

        lblFuncionariosCadastrados.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        lblFuncionariosCadastrados.setText("Funcionários Cadastrados:");

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        botaoAdicionarNovoFuncionario.setText("Adicionar Novo Funcionário");
        botaoAdicionarNovoFuncionario.addActionListener(this::botaoAdicionarNovoFuncionarioActionPerformed);
        jPanel1.add(botaoAdicionarNovoFuncionario);

        botaoExcluir.setText("Excluir Selecionado");
        botaoExcluir.addActionListener(this::botaoExcluirActionPerformed);
        jPanel1.add(botaoExcluir);

        botaoSalvar.setText("Salvar Alterações");
        botaoSalvar.addActionListener(this::botaoSalvarActionPerformed);
        jPanel1.add(botaoSalvar);

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(this::botaoFecharActionPerformed);
        jPanel1.add(botaoFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFuncionariosCadastrados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncionariosCadastrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarNovoFuncionarioActionPerformed
        adicionarFuncionario();
    }//GEN-LAST:event_botaoAdicionarNovoFuncionarioActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        excluirFuncionario();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        salvarAlteracoes();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        fecharJanela();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void carregarDadosNaTabela() {
        modeloTabela.setRowCount(0); 
        List<Funcionario> funcionarios = funcionarioDAO.getTodosOsFuncionarios();
        for (Funcionario f : funcionarios) {
            modeloTabela.addRow(new Object[]{
                f.getCodigo(),
                f.getNome(),
                f.getDataNascimento().format(DATE_FORMATTER),
                f.getSexo(),
                f.getCargo(),
                f.getUsuario(),
                f.getSenha()
            });
        }
        dadosAlterados = false;
    }
    
    private void adicionarFuncionario() {
        // Passo 1: Coletar dados iniciais
        TelaNovoFuncionario telaNovo = new TelaNovoFuncionario((java.awt.Frame) getOwner(), true);
        telaNovo.setVisible(true);
        
        Funcionario funcionarioParcial = telaNovo.getFuncionario();
        
        // Se o primeiro passo foi bem-sucedido e não cancelado
        if (funcionarioParcial != null) {
            // Passo 2: Criar credenciais
            TelaCriarCredenciais telaCredenciais = new TelaCriarCredenciais(this, true, funcionarioParcial);
            telaCredenciais.setVisible(true);
            
            Funcionario funcionarioCompleto = telaCredenciais.getFuncionario();

            // Se o segundo passo foi bem-sucedido e não cancelado
            if (funcionarioCompleto != null) {
                funcionarioDAO.adicionarFuncionario(funcionarioCompleto);
                carregarDadosNaTabela();
                dadosAlterados = true;
            }
        }
    }
    
    private void excluirFuncionario() {
        int linhaSelecionada = tabelaFuncionarios.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um funcionário para excluir.", "Nenhum Funcionário Selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o funcionário selecionado?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Funcionario f = funcionarioDAO.getTodosOsFuncionarios().get(linhaSelecionada);
            funcionarioDAO.removerFuncionario(f);
            carregarDadosNaTabela(); 
            dadosAlterados = true;
        }
    }
    
    private void salvarAlteracoes() {
        if (tabelaFuncionarios.isEditing()) {
            tabelaFuncionarios.getCellEditor().stopCellEditing();
        }

        List<Funcionario> funcionarios = funcionarioDAO.getTodosOsFuncionarios();
        for (int i = 0; i < modeloTabela.getRowCount(); i++) {
            Funcionario f = funcionarios.get(i);
            if(f != null) {
                f.setNome((String) modeloTabela.getValueAt(i, 1));
                try {
                    f.setDataNascimento(LocalDate.parse(modeloTabela.getValueAt(i, 2).toString(), DATE_FORMATTER));
                    f.setSexo((String) modeloTabela.getValueAt(i, 3));
                    f.setCargo((String) modeloTabela.getValueAt(i, 4));
                    f.setUsuario((String) modeloTabela.getValueAt(i, 5));
                    f.setSenha((String) modeloTabela.getValueAt(i, 6));
                } catch(java.time.format.DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Erro de formato de data na linha " + (i+1) + ".\nUse o formato dd/MM/yyyy.", "Erro de Dados", JOptionPane.ERROR_MESSAGE);
                    return; // Interrompe o salvamento
                }
            }
        }
        
        funcionarioDAO.salvarAlteracoes();
        dadosAlterados = false;
        JOptionPane.showMessageDialog(this, "Alterações salvas com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        carregarDadosNaTabela();
    }
    
    private void fecharJanela() {
        if (dadosAlterados) {
            int resposta = JOptionPane.showConfirmDialog(this, "Você possui alterações não salvas. Deseja salvar antes de sair?", "Alterações Pendentes", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION) {
                salvarAlteracoes();
                dispose();
            } else if (resposta == JOptionPane.NO_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaGerenciarFuncionarios dialog = new TelaGerenciarFuncionarios(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarNovoFuncionario;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFuncionariosCadastrados;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaFuncionarios;
    // End of variables declaration//GEN-END:variables
}